spring:
  application:
    name: chat_app

  mongodb:
    uri: "${MONGODB_URI}"
  data:
    mongodb:
      auto-index-creation: true
  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: "${GMAIL_USERNAME:}"
    password: "${GMAIL_PASSWORD:}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID:not-set}"
            client-secret: "${GOOGLE_CLIENT_SECRET:not-set}"
            redirect-uri: "${FRONTEND:http://localhost:3000}/login/oauth2/code/google"


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB


server:
  port: ${PORT:9000}
  forward-headers-strategy: framework


springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs


cloudinary:
  cloud-name: "${CLOUDINARY_CLOUD_NAME:not-set}"
  api-key: "${CLOUDINARY_API_KEY:not-set}"
  api-secret: "${CLOUDINARY_API_SECRET:not-set}"


jwt:
  expiration: "${EXPIRATION:900000}"
  secret: "${SECRET:VGhpcy1pcy1hLWRldi1zZWNyZXQta2V5LWZvci1qbGluZy0yMDI2LXNvbWUtcmFuZG9tLWJhc2U2NA==}"


cookie:
  secure: "${COOKIE_SECURE:false}"


app:
  frontend-url: "${FRONTEND:http://localhost:3000}"


  mail-from: "${mail-from}"

logging:
  level:
    org.springframework.security: DEBUG