spring:
  application:
    name: chat_app

  mongodb:
    uri: mongodb://root:root@mongo_db:27017/chatAppDB?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/chat-app/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9000


springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

storage:
  path: /apps/ChatAppStorage